### ISSUE TITLE
Cannot get local image files to appear in pdf

### ISSUE THREAD

**Issue by appleJax** [AmirTugi/tea-school#5]
Is there a way to get local image files to display in the outputted pdf? I've tried every conceivable relative and absolute path, and nothing has worked so far.

**Comment by AmirTugi** [comment]
Hi
Your issue is something that I myself ran into.
The thing is, it's a [puppeteer issue](https://github.com/GoogleChrome/puppeteer/issues/1472).
They do not allow you to locally display images for security reasons.

There are couple of workarounds I can think of:
1. Serve the static assets (images) yourself (make so you'll be able to access the image by a url (<project-domain>/images/<your-image-name>))
2. Find a free image hosting site to do (1) for you (That's what I did).

**Comment by appleJax** [comment]
Ok, will do. Thanks Amir!
